### ISSUE TITLE
'Option' item disabled?

### ISSUE THREAD

**Issue by PeterDaveHello** [henry40408/awesome-stars#2]
Seems the standard 'Option' item in the (left click)menu of awesome-stars on Google 48.0.2564.116 is disabled, I'm not sure if it's correct behavior, right now only right click on the icon can bring me to the option page.

**Comment by henry40408** [comment]
For the convenience of very early development, I use `chrome.browserAction.onClick` instead of `options_page` to invoke options page. Since the options page is nearly ready now, I added the `options_page` back to `manifest.json` (4d222f8223a12bcce8a5c8dd44829c7771c39c98 and version __1.1.1__), and __the "Options" item in extension context menu should work now__.

The latest version has been uploaded to Chrome Web Store.

However, I am not sure why the right click brings you to options page instead of left click. I use the same version of Chrome.

**Comment by PeterDaveHello** [comment]
> However, I am not sure why the right click brings you to options page instead of left click. I use the same version of Chrome.

I am sorry, I said it wrong, the left click brings you to options page.

**Comment by PeterDaveHello** [comment]
Seems the option item works now on new version, thanks!
